# Generated by Django 3.2.19 on 2024-12-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_user_referred_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonstats',
            name='all_referral_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lessonstats',
            name='month_referral_bonus',
            field=models.IntegerField(default=0),
        ),
    ]
