# Generated by Django 3.2.19 on 2023-09-02 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_alter_newstudent_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newstudent',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.topic'),
        ),
    ]
