# Generated by Django 3.2.19 on 2023-09-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_alter_newstudent_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='newstudent',
            name='level',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='newstudent',
            name='school',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
