# Generated by Django 3.2.19 on 2023-09-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_auto_20230902_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newstudent',
            name='email',
        ),
        migrations.AddField(
            model_name='newstudent',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newstudent',
            name='level',
            field=models.CharField(choices=[('rozwijające', 'Rozwijające'), ('koordynujące', 'Koordynujące')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newstudent',
            name='school',
            field=models.CharField(choices=[('podstawowa', 'Szkoła podstawowa'), ('średnia', 'Szkoła średnia'), ('maturalna', 'Klasa maturalna'), ('wyższa', 'Szkoła wyższa')], max_length=20, null=True),
        ),
    ]
