# Generated by Django 3.2.19 on 2023-09-08 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_auto_20230903_1245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newteacher',
            old_name='language',
            new_name='age_language',
        ),
        migrations.RemoveField(
            model_name='newteacher',
            name='age',
        ),
        migrations.AddField(
            model_name='newteacher',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.topic'),
        ),
    ]
