# Generated by Django 3.2.19 on 2023-09-09 17:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_auto_20230908_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
