# Generated by Django 4.0.6 on 2025-06-23 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_user_add_info_alter_teachersearning_month'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'verbose_name': 'BLOG - Kategorie', 'verbose_name_plural': 'BLOG - Kategorie'},
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'verbose_name': 'BLOG - Posty', 'verbose_name_plural': 'BLOG - Posty'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-updated', '-created'], 'verbose_name': 'STREFA WIEDZY - Komentarze', 'verbose_name_plural': 'STREFA WIEDZY - Komentarze'},
        ),
        migrations.AlterModelOptions(
            name='platformmessage',
            options={'verbose_name': 'Wiadomości', 'verbose_name_plural': 'Wiadomości'},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name': 'STREFA WIEDZY - Zgłoszenia', 'verbose_name_plural': 'STREFA WIEDZY - Zgłoszenia'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-created', '-updated'], 'verbose_name': 'STREFA WIEDZY - Posty', 'verbose_name_plural': 'STREFA WIEDZY - Posty'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'STREFA WIEDZY - Kategorie', 'verbose_name_plural': 'STREFA WIEDZY - Kategorie'},
        ),
        migrations.AlterField(
            model_name='message',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.room'),
        ),
        migrations.AlterField(
            model_name='teachersearning',
            name='month',
            field=models.PositiveIntegerField(default=6),
        ),
    ]
