# Generated by Django 4.0.6 on 2025-07-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_alter_blogcategory_options_alter_blogpost_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachersearning',
            name='month',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
