# Generated by Django 4.0.6 on 2025-08-01 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0033_alter_course_options_remove_course_student_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newstudents',
            options={'verbose_name': 'STREFA KOREPETYCJI - Nowi uczniowie', 'verbose_name_plural': 'STREFA KOREPETYCJI - Nowi uczniowie'},
        ),
        migrations.AddField(
            model_name='newstudents',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Dodatkowe uwagi'),
        ),
        migrations.AlterField(
            model_name='teachersearning',
            name='month',
            field=models.PositiveIntegerField(default=8),
        ),
    ]
