# Generated by Django 3.2.19 on 2023-09-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0034_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='all_lessons',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='lessons',
            field=models.IntegerField(default=0),
        ),
    ]
