# Generated by Django 4.0.6 on 2025-08-02 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0034_alter_newstudents_options_newstudents_notes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonstats',
            options={'verbose_name': 'STREFA KOREPETYCJI - Statystyki', 'verbose_name_plural': 'STREFA KOREPETYCJI - Statystyki'},
        ),
        migrations.DeleteModel(
            name='BankInformation',
        ),
    ]
