# Generated by Django 4.0.6 on 2025-08-03 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0035_alter_lessonstats_options_delete_bankinformation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availability',
            options={'verbose_name': 'STREFA KOREPETYCJI - Dostępności', 'verbose_name_plural': 'STREFA KOREPETYCJI - Dostępności'},
        ),
        migrations.AlterModelOptions(
            name='coursemessage',
            options={'ordering': ['-messageUpdated', '-messageCreated'], 'verbose_name': 'STREFA KOREPETYCJI - Komentarze', 'verbose_name_plural': 'STREFA KOREPETYCJI - Komentarze'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['-postUpdated', '-postCreated'], 'verbose_name': 'STREFA KOREPETYCJI - Lekcje', 'verbose_name_plural': 'STREFA KOREPETYCJI - Lekcje'},
        ),
        migrations.AlterModelOptions(
            name='lessoncorrection',
            options={'verbose_name': 'STREFA KOREPETYCJI - Korekty', 'verbose_name_plural': 'STREFA KOREPETYCJI - Korekty'},
        ),
        migrations.AlterModelOptions(
            name='resign',
            options={'verbose_name': 'STREFA KOREPETYCJI - Rezygnacje', 'verbose_name_plural': 'STREFA KOREPETYCJI - Rezygnacje'},
        ),
        migrations.AlterModelOptions(
            name='teachersearning',
            options={'verbose_name': 'STREFA KOREPETYCJI - Wypłaty', 'verbose_name_plural': 'STREFA KOREPETYCJI - Wypłaty'},
        ),
        migrations.RemoveField(
            model_name='resign',
            name='email',
        ),
    ]
