# Generated by Django 3.2.19 on 2023-09-18 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0035_auto_20230918_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='all_lessons',
            field=models.IntegerField(default=models.IntegerField(default=0)),
        ),
    ]
