# Generated by Django 3.2.19 on 2023-09-18 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0036_alter_user_all_lessons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='all_lessons',
            field=models.IntegerField(default=0),
        ),
    ]
