# Generated by Django 4.0.6 on 2025-08-05 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0036_alter_availability_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonstats',
            name='basic_lesson_rate',
            field=models.DecimalField(decimal_places=2, default=45.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='lessonstats',
            name='intermediate_lesson_rate',
            field=models.DecimalField(decimal_places=2, default=60.0, max_digits=6),
        ),
    ]
