# Generated by Django 4.0.6 on 2025-08-06 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0037_lessonstats_basic_lesson_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateOfConduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='conduct-certificates/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conduct_certificates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
