# Generated by Django 3.2.19 on 2023-10-04 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0038_alter_coursemessage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
