# Generated by Django 4.0.6 on 2025-08-06 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0039_criminalrecord_delete_certificateofconduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CriminalRecord',
        ),
    ]
