# Generated by Django 3.2.19 on 2023-10-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0040_auto_20231008_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
