# Generated by Django 3.2.19 on 2023-10-10 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0041_post_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='points',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
