# Generated by Django 3.2.19 on 2023-10-21 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0044_auto_20231021_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='image',
        ),
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='room_images/'),
        ),
        migrations.DeleteModel(
            name='RoomImage',
        ),
    ]
