# Generated by Django 3.2.19 on 2023-10-21 14:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0046_message_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
