# Generated by Django 3.2.19 on 2023-10-21 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0047_alter_message_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='likes',
        ),
    ]
