# Generated by Django 3.2.19 on 2023-10-29 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0049_roommember'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
