# Generated by Django 3.2.19 on 2023-11-08 21:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0052_rename_participants_count_post_num_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='num_participants',
        ),
        migrations.AddField(
            model_name='post',
            name='students_joined',
            field=models.ManyToManyField(blank=True, related_name='students_joined', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='teachers_joined',
            field=models.ManyToManyField(blank=True, related_name='teachers_joined', to=settings.AUTH_USER_MODEL),
        ),
    ]
