# Generated by Django 3.2.19 on 2023-11-08 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0053_auto_20231108_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='students_joined',
        ),
        migrations.RemoveField(
            model_name='post',
            name='teachers_joined',
        ),
        migrations.AddField(
            model_name='post',
            name='participants_count',
            field=models.IntegerField(default=0),
        ),
    ]
