# Generated by Django 3.2.19 on 2023-11-08 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0054_auto_20231108_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='participants_count',
        ),
    ]
