# Generated by Django 3.2.19 on 2023-11-08 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0055_remove_post_participants_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='num_students_joined',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='num_teachers_joined',
            field=models.IntegerField(default=0),
        ),
    ]
