# Generated by Django 3.2.19 on 2023-11-08 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0056_auto_20231108_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='num_students_joined',
        ),
        migrations.RemoveField(
            model_name='post',
            name='num_teachers_joined',
        ),
    ]
