# Generated by Django 3.2.19 on 2023-11-08 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0058_post_count_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='count_teacher',
        ),
    ]
