# Generated by Django 3.2.19 on 2023-11-08 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0059_remove_post_count_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='participants_count',
            field=models.IntegerField(default=0),
        ),
    ]
