# Generated by Django 3.2.19 on 2023-11-08 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0061_remove_post_participants_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='participants_count',
            field=models.IntegerField(default=0),
        ),
    ]
