# Generated by Django 3.2.19 on 2023-11-08 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0063_remove_post_participants_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='joined_users',
            field=models.TextField(blank=True, null=True),
        ),
    ]
