# Generated by Django 3.2.19 on 2023-11-08 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0065_alter_post_joined_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='joined_users',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
