# Generated by Django 3.2.19 on 2023-11-08 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0067_alter_post_joined_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='joined_users',
        ),
    ]
