# Generated by Django 3.2.19 on 2023-11-09 14:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0068_remove_post_joined_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='lesson_participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
