# Generated by Django 3.2.19 on 2023-11-09 14:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0069_alter_post_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='participants_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='postParticipants', to=settings.AUTH_USER_MODEL),
        ),
    ]
