# Generated by Django 3.2.19 on 2023-11-09 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0070_auto_20231109_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='participants_count',
        ),
    ]
