# Generated by Django 3.2.19 on 2023-11-09 16:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0073_auto_20231109_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roommember',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='enrolled_students',
            field=models.ManyToManyField(blank=True, related_name='postEnrolledStudents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='participants_count',
            field=models.ManyToManyField(blank=True, related_name='post_participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
