# Generated by Django 3.2.19 on 2023-11-09 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0074_auto_20231109_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='enrolled_students',
        ),
        migrations.RemoveField(
            model_name='post',
            name='participants_count',
        ),
        migrations.AddField(
            model_name='post',
            name='participants_count',
            field=models.IntegerField(default=0),
        ),
    ]
