# Generated by Django 3.2.19 on 2023-11-09 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0075_auto_20231109_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='participants_count',
        ),
    ]
