# Generated by Django 3.2.19 on 2023-11-10 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0078_auto_20231110_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='click_count',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Click',
        ),
    ]
