# Generated by Django 3.2.19 on 2023-11-10 09:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0079_auto_20231110_0859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='click_count',
        ),
        migrations.AddField(
            model_name='post',
            name='clicked_by',
            field=models.ManyToManyField(blank=True, related_name='clicked_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
