# Generated by Django 3.2.19 on 2023-11-10 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0080_auto_20231110_0910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='clicked_by',
            new_name='clicked_users',
        ),
    ]
