# Generated by Django 3.2.19 on 2023-11-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0081_rename_clicked_by_post_clicked_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='break_lessons',
            field=models.IntegerField(default=0),
        ),
    ]
