# Generated by Django 3.2.19 on 2023-11-12 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0084_auto_20231110_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
                ('lesson_name', models.CharField(max_length=200)),
                ('report_created', models.DateTimeField(auto_now_add=True)),
                ('students', models.ManyToManyField(blank=True, related_name='lesson_reports_attended', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_reports_given', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
