# Generated by Django 3.2.19 on 2023-11-12 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0085_lessonreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonreport',
            name='course_name',
        ),
        migrations.RemoveField(
            model_name='lessonreport',
            name='lesson_name',
        ),
        migrations.RemoveField(
            model_name='lessonreport',
            name='report_created',
        ),
        migrations.AddField(
            model_name='lessonreport',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_reports', to='website.course'),
        ),
        migrations.AddField(
            model_name='lessonreport',
            name='report_text',
            field=models.TextField(default=''),
        ),
    ]
