# Generated by Django 3.2.19 on 2023-11-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0086_auto_20231112_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonreport',
            name='teacher_participation',
            field=models.BooleanField(default=0),
        ),
    ]
