# Generated by Django 3.2.19 on 2023-11-12 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0087_lessonreport_teacher_participation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonreport',
            name='teacher_participation',
        ),
        migrations.AlterField(
            model_name='lessonreport',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_reports', to='website.course'),
        ),
        migrations.AlterField(
            model_name='lessonreport',
            name='report_text',
            field=models.TextField(),
        ),
    ]
