# Generated by Django 3.2.19 on 2023-11-12 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0089_post_attended_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corrected_points', models.IntegerField(blank=True, null=True)),
                ('corrected_feedback', models.TextField(blank=True, null=True)),
                ('attended_students', models.ManyToManyField(blank=True, related_name='attended_corrections', to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='website.post')),
            ],
            options={
                'verbose_name_plural': 'Lesson Corrections',
            },
        ),
        migrations.DeleteModel(
            name='LessonReport',
        ),
    ]
