# Generated by Django 3.2.19 on 2023-11-12 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0090_auto_20231112_1448'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessoncorrection',
            options={'ordering': ['-lesson__postUpdated', '-lesson__postCreated']},
        ),
        migrations.RemoveField(
            model_name='lessoncorrection',
            name='corrected_feedback',
        ),
        migrations.RemoveField(
            model_name='lessoncorrection',
            name='corrected_points',
        ),
    ]
