# Generated by Django 3.2.19 on 2023-11-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0092_auto_20231112_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessoncorrection',
            name='teacher_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
