# Generated by Django 3.2.19 on 2023-11-12 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0093_lessoncorrection_teacher_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessoncorrection',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.post'),
        ),
    ]
