# Generated by Django 3.2.19 on 2023-11-12 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0094_alter_lessoncorrection_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessoncorrection',
            name='teacher_confirmed',
        ),
        migrations.AlterField(
            model_name='lessoncorrection',
            name='feedback',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='lessoncorrection',
            name='lesson',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='website.post'),
        ),
    ]
