# Generated by Django 3.2.19 on 2023-11-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0096_lessoncorrection_attended_teachers'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessoncorrection',
            name='lesson_image',
            field=models.ImageField(blank=True, null=True, upload_to='lesson_images/'),
        ),
    ]
