# Generated by Django 3.2.19 on 2023-11-19 12:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0097_lessoncorrection_lesson_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='attended_teachers',
            field=models.ManyToManyField(blank=True, related_name='attended_teachers_lessons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='attended_students',
            field=models.ManyToManyField(blank=True, related_name='attended_students_lessons', to=settings.AUTH_USER_MODEL),
        ),
    ]
