# Generated by Django 3.2.19 on 2023-11-19 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0098_auto_20231119_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='feedback',
        ),
    ]
