# Generated by Django 3.2.19 on 2023-11-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0099_remove_post_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='feedback',
            field=models.TextField(blank=True, default='-', null=True),
        ),
    ]
