# Generated by Django 3.2.19 on 2023-11-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0100_post_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
