# Generated by Django 3.2.19 on 2023-11-28 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0101_alter_post_feedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursemessage',
            options={'ordering': ['-messageUpdated', '-messageCreated']},
        ),
        migrations.AlterField(
            model_name='newstudent',
            name='level',
            field=models.CharField(choices=[('rozwijające', 'Rozwijające'), ('korygujące', 'Korygujące')], max_length=20, null=True),
        ),
    ]
