# Generated by Django 3.2.19 on 2023-12-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0104_alter_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='feedback_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
