# Generated by Django 3.2.19 on 2023-12-22 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0107_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(default='-', null=True),
        ),
        migrations.DeleteModel(
            name='Availability',
        ),
    ]
