# Generated by Django 3.2.19 on 2024-01-09 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0109_hourrange_teacheravailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='student',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='course',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.CreateModel(
            name='Resign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('reason', models.CharField(choices=[('Przerwa', 'Przerwa'), ('Rezygnacja', 'Rezygnacja')], max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('course_info', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
