# Generated by Django 3.2.19 on 2024-01-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0110_auto_20240109_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='resign',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, 'Źle'), (2, 'Słabo'), (3, 'Przeciętnie'), (4, 'Dobrze'), (5, 'Fantastycznie')], null=True),
        ),
    ]
