# Generated by Django 3.2.19 on 2024-01-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0111_resign_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='resign',
            name='consider_return',
            field=models.CharField(blank=True, choices=[('Tak', 'Tak'), ('Nie', 'Nie')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='resign',
            name='reason_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
