# Generated by Django 3.2.19 on 2024-02-02 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0112_auto_20240109_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('tutor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='teacheravailability',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='teacheravailability',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='HourRange',
        ),
        migrations.DeleteModel(
            name='TeacherAvailability',
        ),
    ]
