# Generated by Django 3.2.19 on 2024-02-02 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0115_auto_20240202_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='tutoravailability',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='tutoravailability',
            name='start_time',
        ),
        migrations.AddField(
            model_name='tutoravailability',
            name='hours',
            field=models.ManyToManyField(to='website.TimeSlot'),
        ),
    ]
