# Generated by Django 3.2.19 on 2024-02-03 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0117_auto_20240202_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='message-files/'),
        ),
    ]
