# Generated by Django 3.2.19 on 2024-02-05 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0119_message_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lessons_intermediate',
            field=models.IntegerField(default=0),
        ),
    ]
