# Generated by Django 3.2.19 on 2024-02-05 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0120_user_lessons_intermediate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='all_lessons_intermediate',
            field=models.IntegerField(default=0),
        ),
    ]
