# Generated by Django 3.2.19 on 2024-02-26 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0123_user_add_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='add_info',
            field=models.TextField(default='Dodaj opis...', max_length=100, null=True),
        ),
    ]
