# Generated by Django 3.2.19 on 2024-02-26 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0124_alter_user_add_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='add_info',
            field=models.CharField(default='Dodaj opis...', max_length=100),
        ),
    ]
