# Generated by Django 3.2.19 on 2024-02-26 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0125_alter_user_add_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='add_info',
            field=models.CharField(default='rola/przedmiot', max_length=100),
        ),
    ]
