# Generated by Django 3.2.19 on 2024-06-04 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0126_alter_user_add_info'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactMessage',
            new_name='PlatformMessage',
        ),
    ]
