# Generated by Django 3.2.19 on 2024-08-15 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0128_auto_20240714_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.CharField(choices=[('SPAM', 'Spam'), ('INAPPROPRIATE', 'Nieodpowiednia treść'), ('HARASSMENT', 'Nękanie'), ('FALSE_INFO', 'Fałszywe informacje'), ('HATE_SPEECH', 'Mowa nienawiści'), ('VIOLENCE', 'Przemoc'), ('COPYRIGHT', 'Naruszenie praw autorskich'), ('OTHER', 'Inne')], max_length=20),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar.svg', null=True, upload_to=''),
        ),
    ]
