# Generated by Django 3.2.19 on 2024-08-19 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0129_auto_20240815_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='profile-pictures/avatar.svg', null=True, upload_to='profile-pictures/'),
        ),
    ]
