# Generated by Django 5.1 on 2024-09-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0133_blogcategory_blogpost_contentblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('basic', 'Podstawowy'), ('intermediate', 'Rozszerzony')], default='basic', max_length=20),
        ),
    ]
