# Generated by Django 5.1 on 2024-09-02 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0134_course_course_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='title',
        ),
    ]
