# Generated by Django 5.1 on 2024-09-10 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0135_remove_course_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='svg_icon',
            field=models.FileField(blank=True, null=True, upload_to='icons/'),
        ),
    ]
