# Generated by Django 5.1 on 2024-10-06 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0136_topic_svg_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog-category-images/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog-list-images/'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog-details-images/'),
        ),
    ]
