# Generated by Django 5.1 on 2024-10-14 00:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0138_post_invite_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoomMember',
        ),
        migrations.RemoveField(
            model_name='newteacher',
            name='name',
        ),
        migrations.AddField(
            model_name='newteacher',
            name='first_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='newteacher',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='newteacher',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Numer telefonu musi być w formacie: '999 999 999'. Maksymalnie 15 cyfr.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
