# Generated by Django 5.1 on 2024-10-14 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0139_delete_roommember_remove_newteacher_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newstudent',
            name='name',
        ),
        migrations.AddField(
            model_name='newstudent',
            name='first_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='newstudent',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
