# Generated by Django 3.2.19 on 2024-11-06 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0141_bankinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='interests',
            field=models.TextField(blank=True, default='Brak zainteresowań', null=True),
        ),
    ]
