# Generated by Django 3.2.19 on 2024-11-20 00:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0143_rename_post_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='all_break_lessons',
        ),
        migrations.RemoveField(
            model_name='user',
            name='all_lessons',
        ),
        migrations.RemoveField(
            model_name='user',
            name='all_lessons_intermediate',
        ),
        migrations.RemoveField(
            model_name='user',
            name='all_missed_lessons',
        ),
        migrations.RemoveField(
            model_name='user',
            name='break_lessons',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lessons',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lessons_intermediate',
        ),
        migrations.RemoveField(
            model_name='user',
            name='missed_lessons',
        ),
        migrations.CreateModel(
            name='LessonStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessons', models.IntegerField(default=0)),
                ('lessons_intermediate', models.IntegerField(default=0)),
                ('break_lessons', models.IntegerField(default=0)),
                ('all_break_lessons', models.IntegerField(default=0)),
                ('missed_lessons', models.IntegerField(default=0)),
                ('all_missed_lessons', models.IntegerField(default=0)),
                ('all_lessons', models.IntegerField(default=0)),
                ('all_lessons_intermediate', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_stats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
