# Generated by Django 3.2.19 on 2024-11-27 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0144_auto_20241120_0005'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherEarnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_lessons_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('monthly_lessons_intermediate_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('monthly_break_lessons_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('monthly_missed_lessons_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('monthly_total_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_lessons_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_lessons_intermediate_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_break_lessons_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_missed_lessons_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_earnings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
