# Generated by Django 3.2.19 on 2024-12-08 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0145_teacherearnings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeacherEarnings',
        ),
    ]
