# Generated by Django 3.2.19 on 2024-12-08 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0147_userearnings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserEarnings',
            new_name='TeachersEarning',
        ),
    ]
