# Generated by Django 3.2.19 on 2024-12-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0148_rename_userearnings_teachersearning'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availability',
            options={'verbose_name': 'Dostępności', 'verbose_name_plural': 'Dostępności'},
        ),
        migrations.AlterModelOptions(
            name='bankinformation',
            options={'verbose_name': 'Informacje bankowe', 'verbose_name_plural': 'Informacje bankowe'},
        ),
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'verbose_name': 'Kategorie - Blog', 'verbose_name_plural': 'Kategorie - Blog'},
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'verbose_name': 'Posty - Blog', 'verbose_name_plural': 'Posty - Blog'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Kursy - Strefa Korepetycji', 'verbose_name_plural': 'Kursy - Strefa Korepetycji'},
        ),
        migrations.AlterModelOptions(
            name='coursemessage',
            options={'verbose_name': 'Komentarze - Strefa Korepetycji', 'verbose_name_plural': 'Komentarze - Strefa Korepetycji'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Lekcje - Strefa Korepetycji', 'verbose_name_plural': 'Lekcje - Strefa Korepetycji'},
        ),
        migrations.AlterModelOptions(
            name='lessoncorrection',
            options={'verbose_name': 'Poprawki lekcji', 'verbose_name_plural': 'Poprawki lekcji'},
        ),
        migrations.AlterModelOptions(
            name='lessonstats',
            options={'verbose_name': 'Lekcje - statystyki', 'verbose_name_plural': 'Lekcje - statystyki'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Komentarze - Strefa Wiedzy', 'verbose_name_plural': 'Komentarze - Strefa Wiedzy'},
        ),
        migrations.AlterModelOptions(
            name='newstudent',
            options={'verbose_name': 'Nowi uczniowie', 'verbose_name_plural': 'Nowi uczniowie'},
        ),
        migrations.AlterModelOptions(
            name='newteacher',
            options={'verbose_name': 'Nowi korepetytorzy', 'verbose_name_plural': 'Nowi korepetytorzy'},
        ),
        migrations.AlterModelOptions(
            name='platformmessage',
            options={'verbose_name': 'Wiadomości z Platformy', 'verbose_name_plural': 'Wiadomości z Platformy'},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name': 'Zgłoszenia - Strefa Wiedzy', 'verbose_name_plural': 'Zgłoszenia - Strefa Wiedzy'},
        ),
        migrations.AlterModelOptions(
            name='resign',
            options={'verbose_name': 'Rezygnacje', 'verbose_name_plural': 'Rezygnacje'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Posty - Strefa Wiedzy', 'verbose_name_plural': 'Posty - Strefa Wiedzy'},
        ),
        migrations.AlterModelOptions(
            name='teachersearning',
            options={'verbose_name': 'Wypłaty', 'verbose_name_plural': 'Wypłaty'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'Kategorie - Strefa Wiedzy', 'verbose_name_plural': 'Kategorie - Strefa Wiedzy'},
        ),
        migrations.AddField(
            model_name='teachersearning',
            name='month',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AddField(
            model_name='teachersearning',
            name='year',
            field=models.PositiveIntegerField(default=2024),
        ),
    ]
