# Generated by Django 3.2.19 on 2024-12-08 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0149_auto_20241208_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachersearning',
            name='total_earnings',
        ),
    ]
