# Generated by Django 3.2.19 on 2024-12-08 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0150_remove_teachersearning_total_earnings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teachersearning',
            options={'verbose_name': 'Wypłata', 'verbose_name_plural': 'Wypłaty'},
        ),
        migrations.AlterUniqueTogether(
            name='teachersearning',
            unique_together={('user', 'month', 'year')},
        ),
    ]
